# Generated by Django 4.2.7 on 2025-08-29 04:55

import django.contrib.postgres.indexes
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier for this integration.",
                        unique=True,
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="ID of the user who owns this integration.",
                    ),
                ),
                (
                    "step",
                    models.PositiveIntegerField(
                        help_text="Current step in the integration process."
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="General integration data.",
                        null=True,
                    ),
                ),
                (
                    "store_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Store-specific data for the integration.",
                        null=True,
                    ),
                ),
                (
                    "api_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="API-related data for the integration.",
                        null=True,
                    ),
                ),
                (
                    "fields_mapping_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Field mapping configuration data.",
                        null=True,
                    ),
                ),
                (
                    "seo_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="SEO-related data for the integration.",
                        null=True,
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Product or integration specifications.",
                        null=True,
                    ),
                ),
                (
                    "unique_identifier",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Unique identifier data for the integration.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Status of the integration.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the integration was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the integration was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
                "db_table": "integrations",
                "ordering": ["-created_at"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["data"], name="integration_data_aa95df_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["store_data"], name="integration_store_d_2a8cba_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["api_data"], name="integration_api_dat_d3f1d4_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["fields_mapping_data"],
                        name="integration_fields__1edbc5_gin",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["seo_data"], name="integration_seo_dat_1a9f02_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["specifications"], name="integration_specifi_9d6a24_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["unique_identifier"],
                        name="integration_unique__2a8ada_gin",
                    ),
                ],
            },
        ),
    ]
