import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/src/components/navbar";
export const metadata: Metadata = {
  title: "Jula Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-white">
        {/* 👇 Navbar yahan lagaya hai taake top par aye */}
        <Navbar />

        {/* Baaki content iske neeche ayega */}
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}